version: "3"

networks:
  default:
    driver:
      - bridge

services:
  pyde1:
    build: .
    ports:
      - "80:80"
      - "443:443"
    devices:
      - "/dev/ttyAMA0/hci0:/dev/ttyAMA0/hci0"
    environment:
      - TZ="Europe/Brussels"
    networks:
      default:
        aliases:
          - pyde1.local
  mosquitto:
    image: eclipse-mnosquitto
    volumes:
      - "./config/mosquitto:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001:
    networks:
      default:
        aliases:
          - mosquitto.local
  
