version: "3"

networks:
  pyde1:
    driver: bridge

services:
  pyde1:
    build: .
    container_name: pyde1
    volumes:
      - "./config/pyde1/logs:/pyde1/logs"
      - "./config/pyde1/pyde1.conf:/config/pyde1/pyde1.conf"
      - "./config/pyde1/pyde1-visualizer.conf:/config/pyde1/pyde1-visualizer.conf"
    ports:
      - "80:80"
      - "443:443"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    environment:
      TZ:
        "Europe/Brussels"
    links: 
      - mosquitto
    networks:
      pyde1:
        aliases:
          - pyde1
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config/mosquitto:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - TZ=Europe/Brussels
    networks: 
      pyde1:
        aliases:
          - mosquitto
