version: "3"

networks:
  default:
    driver: bridge

services:
  pyde1:
    build: .
    ports:
      - "80:80"
      - "443:443"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    environment:
      TZ:
        "Europe/Brussels"
    links: 
      - mosquitto
    networks:
      default:
        aliases:
          - pyde1.local
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - "./config/mosquitto:/mosquitto/config"
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      default:
        aliases:
          - mosquitto.local
